'use client'

import { useState } from 'react'

interface ReportSection { heading: string; content?: string; table?: { headers: string[]; rows: string[][] } }
interface Report { title: string; subtitle: string; sections: ReportSection[] }
type Template = 'monthly_monitoring' | 'gtco_metrics' | 'executive_snapshot' | 'audit_evidence'

const TEMPLATES: { key: Template; title: string; desc: string }[] = [
  { key: 'monthly_monitoring', title: 'Monthly Monitoring Summary', desc: 'Signals monitored, actions taken, policy reviews triggered' },
  { key: 'gtco_metrics', title: 'GTCO Metrics Support Pack', desc: 'Information security metrics for subsidiary reporting' },
  { key: 'executive_snapshot', title: 'Executive Snapshot', desc: 'Key changes, risks, open items for leadership' },
  { key: 'audit_evidence', title: 'Audit Evidence Summary', desc: 'Complete evidence trail for audit and review' },
]

function getDefaultPeriod() {
  const now = new Date()
  return { start: new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split('T')[0], end: new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().split('T')[0] }
}

function reportToCSV(report: Report): string {
  const lines: string[] = [report.title, report.subtitle, '']
  for (const s of report.sections) { lines.push(s.heading); if (s.content) lines.push(s.content); if (s.table) { lines.push(s.table.headers.map(h => `"${h}"`).join(',')); for (const row of s.table.rows) lines.push(row.map(c => `"${c}"`).join(',')) }; lines.push('') }
  return lines.join('\n')
}

function reportToHTML(report: Report): string {
  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${report.title}</title><style>body{font-family:Inter,system-ui,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#1a1d2e;font-size:13px;line-height:1.6}h1{font-size:20px;margin-bottom:4px;font-weight:800}.subtitle{color:#8b90a5;font-size:14px;margin-bottom:32px}h2{font-size:14px;color:#1a1d2e;border-bottom:1px solid #eef0f4;padding-bottom:6px;margin-top:28px;font-weight:600}table{width:100%;border-collapse:collapse;margin:12px 0}th{text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:0.08em;color:#8b90a5;padding:8px;border-bottom:2px solid #eef0f4}td{padding:8px;border-bottom:1px solid #f4f6fa;font-size:12px}tr:hover{background:#f8f9fc}p{margin:8px 0}.footer{margin-top:40px;padding-top:16px;border-top:1px solid #eef0f4;color:#8b90a5;font-size:11px}@media print{body{margin:20px}}</style></head><body><h1>${report.title}</h1><div class="subtitle">${report.subtitle}</div>`
  for (const s of report.sections) { html += `<h2>${s.heading}</h2>`; if (s.content) html += `<p>${s.content}</p>`; if (s.table) { html += '<table><thead><tr>'; for (const h of s.table.headers) html += `<th>${h}</th>`; html += '</tr></thead><tbody>'; for (const row of s.table.rows) { html += '<tr>'; for (const cell of row) html += `<td>${cell}</td>`; html += '</tr>' }; html += '</tbody></table>' } }
  html += `<div class="footer">Generated by RegWatch · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div></body></html>`
  return html
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; a.click(); URL.revokeObjectURL(url)
}

export default function ReportsPage() {
  const defaults = getDefaultPeriod()
  const [selected, setSelected] = useState<Template | null>(null)
  const [start, setStart] = useState(defaults.start)
  const [end, setEnd] = useState(defaults.end)
  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState<Report | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function generate() {
    if (!selected) return; setLoading(true); setError(null); setReport(null)
    try { const res = await fetch('/api/reports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ template: selected, period_start: start, period_end: end }) }); if (!res.ok) { setError((await res.json()).error || 'Failed'); return }; setReport((await res.json()).report) } catch { setError('Network error') } finally { setLoading(false) }
  }

  async function exportReport(format: 'pdf' | 'csv') {
    if (!report || !selected) return
    fetch('/api/reports', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ template: selected, format }) }).catch(() => {})
    const safeName = report.title.toLowerCase().replace(/\s+/g, '-')
    if (format === 'csv') { downloadBlob(reportToCSV(report), `${safeName}.csv`, 'text/csv') }
    else { const html = reportToHTML(report); const win = window.open('', '_blank'); if (win) { win.document.write(html); win.document.close(); setTimeout(() => win.print(), 500) } }
  }

  return (
    <div className="space-y-6">
      <div><h1 className="rw-page-title">Reports</h1><p className="rw-page-subtitle">Generate monitoring summaries and compliance reports.</p></div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {TEMPLATES.map(t => (
          <button key={t.key} onClick={() => { setSelected(t.key); setReport(null) }}
            className={`text-left rw-card p-5 transition-all duration-150 ${selected === t.key ? 'ring-2 ring-indigo-500 border-indigo-200' : 'hover:shadow-md'}`}>
            <h3 className="text-[13px] font-semibold" style={{ color: '#0f1121' }}>{t.title}</h3>
            <p className="text-[11px] mt-1.5 leading-relaxed" style={{ color: '#8b90a5' }}>{t.desc}</p>
          </button>
        ))}
      </div>

      {selected && (
        <div className="rw-card p-5">
          <div className="flex flex-wrap items-end gap-4">
            <div><label className="rw-label">Period Start</label><input type="date" value={start} onChange={e => setStart(e.target.value)} className="rw-input w-auto" /></div>
            <div><label className="rw-label">Period End</label><input type="date" value={end} onChange={e => setEnd(e.target.value)} className="rw-input w-auto" /></div>
            <button onClick={generate} disabled={loading} className="rw-btn-primary">{loading ? 'Generating…' : 'Generate Report'}</button>
          </div>
          {error && <p className="text-[12px] text-red-600 mt-2">{error}</p>}
        </div>
      )}

      {report && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-[14px] font-semibold" style={{ color: '#1a1d2e' }}>Preview</h2>
            <div className="flex gap-2"><button onClick={() => exportReport('pdf')} className="rw-btn-secondary">Export PDF</button><button onClick={() => exportReport('csv')} className="rw-btn-secondary">Export CSV</button></div>
          </div>
          <div className="rw-card p-6 space-y-6">
            <div><h1 className="text-[18px] font-extrabold tracking-tight" style={{ color: '#0f1121' }}>{report.title}</h1><p className="text-[13px]" style={{ color: '#8b90a5' }}>{report.subtitle}</p></div>
            {report.sections.map((section, i) => (
              <div key={i}>
                <h3 className="text-[13px] font-semibold pb-1.5 mb-3" style={{ color: '#1a1d2e', borderBottom: '1px solid #eef0f4' }}>{section.heading}</h3>
                {section.content && <p className="text-[12px] leading-relaxed" style={{ color: '#3a3f56' }}>{section.content}</p>}
                {section.table && (
                  <div className="overflow-x-auto mt-2"><table className="rw-table"><thead><tr>{section.table.headers.map((h, j) => <th key={j}>{h}</th>)}</tr></thead><tbody>{section.table.rows.map((row, j) => <tr key={j}>{row.map((cell, k) => <td key={k}>{cell}</td>)}</tr>)}</tbody></table></div>
                )}
              </div>
            ))}
            <p className="text-[10px] pt-4" style={{ color: '#8b90a5', borderTop: '1px solid #eef0f4' }}>Generated by RegWatch · {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
          </div>
        </div>
      )}
    </div>
  )
}
