'use client'

import { useState } from 'react'

/* ── Types ────────────────────────────────────────────────── */

interface ReportSection {
  heading: string
  content?: string
  table?: { headers: string[]; rows: string[][] }
}

interface Report {
  title: string
  subtitle: string
  sections: ReportSection[]
}

type Template = 'monthly_monitoring' | 'gtco_metrics' | 'executive_snapshot' | 'audit_evidence'

const TEMPLATES: { key: Template; title: string; desc: string }[] = [
  { key: 'monthly_monitoring', title: 'Monthly Monitoring Summary', desc: 'Signals monitored, actions taken, policy reviews triggered' },
  { key: 'gtco_metrics', title: 'GTCO Metrics Support Pack', desc: 'Information security metrics for subsidiary reporting' },
  { key: 'executive_snapshot', title: 'Executive Snapshot', desc: 'Key changes, risks, open items for leadership' },
  { key: 'audit_evidence', title: 'Audit Evidence Summary', desc: 'Complete evidence trail for audit and review' },
]

/* ── Helpers ──────────────────────────────────────────────── */

function getDefaultPeriod(): { start: string; end: string } {
  const now = new Date()
  const start = new Date(now.getFullYear(), now.getMonth(), 1)
  const end = new Date(now.getFullYear(), now.getMonth() + 1, 0)
  return {
    start: start.toISOString().split('T')[0],
    end: end.toISOString().split('T')[0],
  }
}

function reportToCSV(report: Report): string {
  const lines: string[] = [report.title, report.subtitle, '']

  for (const section of report.sections) {
    lines.push(section.heading)
    if (section.content) lines.push(section.content)
    if (section.table) {
      lines.push(section.table.headers.map(h => `"${h}"`).join(','))
      for (const row of section.table.rows) {
        lines.push(row.map(c => `"${c}"`).join(','))
      }
    }
    lines.push('')
  }

  return lines.join('\n')
}

function reportToHTML(report: Report): string {
  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${report.title}</title>
<style>
body{font-family:system-ui,-apple-system,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;color:#1e293b;font-size:13px;line-height:1.6}
h1{font-size:20px;margin-bottom:4px}
.subtitle{color:#64748b;font-size:14px;margin-bottom:32px}
h2{font-size:14px;color:#334155;border-bottom:1px solid #e2e8f0;padding-bottom:6px;margin-top:28px}
table{width:100%;border-collapse:collapse;margin:12px 0}
th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;color:#64748b;padding:8px;border-bottom:2px solid #e2e8f0}
td{padding:8px;border-bottom:1px solid #f1f5f9;font-size:12px}
tr:hover{background:#f8fafc}
p{margin:8px 0}
.footer{margin-top:40px;padding-top:16px;border-top:1px solid #e2e8f0;color:#94a3b8;font-size:11px}
@media print{body{margin:20px}h1{font-size:18px}}
</style></head><body>
<h1>${report.title}</h1>
<div class="subtitle">${report.subtitle}</div>`

  for (const section of report.sections) {
    html += `<h2>${section.heading}</h2>`
    if (section.content) html += `<p>${section.content}</p>`
    if (section.table) {
      html += '<table><thead><tr>'
      for (const h of section.table.headers) html += `<th>${h}</th>`
      html += '</tr></thead><tbody>'
      for (const row of section.table.rows) {
        html += '<tr>'
        for (const cell of row) html += `<td>${cell}</td>`
        html += '</tr>'
      }
      html += '</tbody></table>'
    }
  }

  html += `<div class="footer">Generated by RegWatch · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>`
  html += '</body></html>'
  return html
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

/* ── Main Page ────────────────────────────────────────────── */

export default function ReportsPage() {
  const defaults = getDefaultPeriod()
  const [selected, setSelected] = useState<Template | null>(null)
  const [start, setStart] = useState(defaults.start)
  const [end, setEnd] = useState(defaults.end)
  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState<Report | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function generate() {
    if (!selected) return
    setLoading(true)
    setError(null)
    setReport(null)
    try {
      const res = await fetch('/api/reports', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ template: selected, period_start: start, period_end: end }),
      })
      if (!res.ok) {
        const data = await res.json()
        setError(data.error || 'Failed to generate report')
        return
      }
      const data = await res.json()
      setReport(data.report)
    } catch {
      setError('Network error generating report')
    } finally {
      setLoading(false)
    }
  }

  async function exportReport(format: 'pdf' | 'csv') {
    if (!report || !selected) return

    fetch('/api/reports', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ template: selected, format }),
    }).catch(() => {})

    const safeName = report.title.toLowerCase().replace(/\s+/g, '-')

    if (format === 'csv') {
      downloadBlob(reportToCSV(report), `${safeName}.csv`, 'text/csv')
    } else {
      const html = reportToHTML(report)
      const win = window.open('', '_blank')
      if (win) {
        win.document.write(html)
        win.document.close()
        setTimeout(() => win.print(), 500)
      }
    }
  }

  return (
    <div className="space-y-5">
      <div>
        <h1 className="rw-page-title">Reports</h1>
        <p className="rw-page-subtitle">Generate monthly monitoring summaries and compliance reports.</p>
      </div>

      {/* Template cards */}
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3">
        {TEMPLATES.map(t => (
          <button key={t.key} onClick={() => { setSelected(t.key); setReport(null) }}
            className={`text-left rw-card p-4 transition-all ${
              selected === t.key
                ? 'ring-2 ring-blue-500 bg-blue-50/50'
                : 'hover:shadow-sm'
            }`}>
            <h3 className="text-[13px] font-semibold text-slate-800">{t.title}</h3>
            <p className="text-[11px] text-slate-500 mt-1.5 leading-relaxed">{t.desc}</p>
          </button>
        ))}
      </div>

      {/* Filters + Generate */}
      {selected && (
        <div className="rw-card p-4">
          <div className="flex flex-wrap items-end gap-4">
            <div>
              <label className="rw-label">Period Start</label>
              <input type="date" value={start} onChange={e => setStart(e.target.value)} className="rw-input w-auto" />
            </div>
            <div>
              <label className="rw-label">Period End</label>
              <input type="date" value={end} onChange={e => setEnd(e.target.value)} className="rw-input w-auto" />
            </div>
            <button onClick={generate} disabled={loading} className="rw-btn-primary">
              {loading ? 'Generating…' : 'Generate Report'}
            </button>
          </div>
          {error && <p className="text-[12px] text-red-600 mt-2">{error}</p>}
        </div>
      )}

      {/* Report Preview */}
      {report && (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-semibold text-slate-700">Preview</h2>
            <div className="flex gap-2">
              <button onClick={() => exportReport('pdf')} className="rw-btn-secondary">Export PDF</button>
              <button onClick={() => exportReport('csv')} className="rw-btn-secondary">Export CSV</button>
            </div>
          </div>

          <div className="rw-card p-6 space-y-6">
            <div>
              <h1 className="text-lg font-bold text-slate-900">{report.title}</h1>
              <p className="text-[13px] text-slate-500">{report.subtitle}</p>
            </div>

            {report.sections.map((section, i) => (
              <div key={i}>
                <h3 className="text-[13px] font-semibold text-slate-700 border-b border-gray-100 pb-1.5 mb-3">{section.heading}</h3>
                {section.content && <p className="text-[12px] text-slate-600 leading-relaxed">{section.content}</p>}
                {section.table && (
                  <div className="overflow-x-auto mt-2">
                    <table className="rw-table">
                      <thead>
                        <tr>
                          {section.table.headers.map((h, j) => (
                            <th key={j}>{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {section.table.rows.map((row, j) => (
                          <tr key={j}>
                            {row.map((cell, k) => (
                              <td key={k}>{cell}</td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            ))}

            <p className="text-[10px] text-slate-400 pt-4 border-t border-gray-100">
              Generated by RegWatch · {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
            </p>
          </div>
        </div>
      )}
    </div>
  )
}
